### ISSUE TITLE
Changed all the poster from the one I selected in FR to ENG

### ISSUE THREAD

**Issue by Nuclead** [mrbuckwheet/Kometa-Config#7]
Like said in the title, when i ran it it changed the all the posters to eng, how do i tell it to keep the one i manually selected ?

Thanks,

**Comment by mrbuckwheet** [comment]
Can you share your logs? Was anything changed from the config? The script doesn't have any poster updates enabled so any posters that are already matched or manually updated in plex are the ones the overlays will be applied to.

**Comment by Nuclead** [comment]
I was running the basic config then i deleted all the files in the config folder, put the minimalist ones and ran the script with the argument to delete the collection (original config file didnt change the posters)

**Comment by Nuclead** [comment]
Tried again on a test library with 3 movies. I manualy chose 3 french posters, ran the script and it changed one of the 3 to the english one but didnt touch the others 2 at all.

**Comment by mrbuckwheet** [comment]
For each of the collection builders you will need to add under template_variables, language: fr since the default value for all of the builders is English. Also change under settings: tvdb_language to fr. Send me a DM on discord @mrbuckwheet as I would like to see the results and help in real time

![Screenshot 2024-11-26 092547](https://github.com/user-attachments/assets/b8620e2a-09dc-4365-9b23-2639480c1e5b)

**Comment by mrbuckwheet** [comment]
added the region and language codes into tmdb

```
tmdb:
  apikey: ################################
  language: en
  region: US
  cache_expiration: 60
```

**Comment by mrbuckwheet** [comment]
added the region and language codes into tmdb

```
tmdb:
  apikey: ################################
  language: en
  region: US
  cache_expiration: 60
```
